// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderApp.DAL;

#nullable disable

namespace OrderApp.DAL.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20230217063137_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderApp.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderApp.Models.OrderWindow", b =>
                {
                    b.Property<int>("WindowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WindowId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOfWindow")
                        .HasColumnType("int");

                    b.Property<string>("WindowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WindowId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderWindows");
                });

            modelBuilder.Entity("OrderApp.Models.OrderWindowDetail", b =>
                {
                    b.Property<int>("WindowDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WindowDetailsId"));

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("OrderWindowId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("WindowDetailsId");

                    b.HasIndex("OrderWindowId");

                    b.ToTable("OrderWindowDetails");
                });

            modelBuilder.Entity("OrderApp.Models.OrderWindow", b =>
                {
                    b.HasOne("OrderApp.Models.Order", "Order")
                        .WithMany("OrderWindows")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderApp.Models.OrderWindowDetail", b =>
                {
                    b.HasOne("OrderApp.Models.OrderWindow", "OrderWindow")
                        .WithMany("OrderWindowDetails")
                        .HasForeignKey("OrderWindowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderWindow");
                });

            modelBuilder.Entity("OrderApp.Models.Order", b =>
                {
                    b.Navigation("OrderWindows");
                });

            modelBuilder.Entity("OrderApp.Models.OrderWindow", b =>
                {
                    b.Navigation("OrderWindowDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
